Algoritmo "contagem_Progressiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Utilizar a estrutura Enquanto, e imprimir os números de 0 a 20
// Contagem Progressiva
// Autor(a)    : Rogerio Curtio
// Data atual  : 04/05/2025
Var
   i : Inteiro

Inicio

      // Contagem Progressiva
      i <- 0
      Enquanto (i <= 20) Faça
           Escreva(i)
           i <- i + 1
      FimEnquanto

Fimalgoritmo