Algoritmo "Contagem_Regressiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Utilizar a estrutura Repita, e imprimir os números de 20 a 1
// Autor(a)    : Rogerio Curtio
// Data atual  : 05/05/2025
Var
   i : Inteiro

Inicio
      // Inicializar
      i <- 20
      Repita
            Escreva(i)
          // Decrementar
          i <- i - 1
      Ate i < 1
Fimalgoritmo