Algoritmo "Contagem_Progressiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Utilizar a estrutura Repita, e imprimir os números de 1 a 40
// Autor(a)    : Rogerio Curtio
// Data atual  : 05/05/2025
Var
   i : Inteiro


Inicio

      // Inicializar
      i <- 1
      Repita
            Escreva(i)
          // incrementar
          i <- i + 1
      Ate i > 40

Fimalgoritmo