Algoritmo "contagem_Regressiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Utilizar a estrutura enquanto, e imprimir os números de 20 a 0
// Contagem Regressiva
// Autor(a)    : Rogerio Curtio
// Data atual  : 04/05/2025
Var
   i : Inteiro

Inicio

      // Contagem Regressiva
      i <- 20
      Enquanto (i >= 0) Faça
           Escreva(i)
           i <- i - 1
      FimEnquanto

Fimalgoritmo